version: "3.1"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    command: bash -c 'sleep 3 && npm start'
    volumes:
      - "./app:/app"

  caddy:
      image: caddy:latest
      container_name: caddy
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - app

volumes:
  caddy_data:
  caddy_config: