version: "3.1"

services:

  app:
    image: vasilevpg/devops-for-programmers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: app
    restart: always
    command: bash -c 'sleep 3 && npm test'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: