# Версия схемы, которую мы используем.
# Зависит от установленной версии docker
# https://docs.docker.com/compose/compose-file/
version: "3.1"
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    image: vasilevpg/devops-for-programmers-project-74
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя докерфайла из которого будет собран образ
      dockerfile: Dockerfile.production
    depends_on: 
      - postgres
    container_name: app
    command: npm test

  # db:
  #   container_name: db
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     # POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     # POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data